# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dungeon.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dungeon.proto',
  package='dungeon',
  serialized_pb='\n\rdungeon.proto\x12\x07\x64ungeon\"#\n\x06Status\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\"_\n\x06Header\x12\x1f\n\x06status\x18\x01 \x01(\x0b\x32\x0f.dungeon.Status\x12\x10\n\x08msg_hash\x18\x02 \x01(\x07\x12\r\n\x05token\x18\x03 \x01(\x05\x12\x13\n\x0bis_response\x18\x04 \x01(\x08\"H\n\x08OpenGame\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x17\n\x0fmax_num_players\x18\x02 \x01(\x05\x12\x17\n\x0f\x63ur_num_players\x18\x03 \x01(\x05\"\x14\n\x12LobbyStatusRequest\"W\n\x13LobbyStatusResponse\x12\x19\n\x11num_running_games\x18\x01 \x01(\x05\x12%\n\nopen_games\x18\x02 \x03(\x0b\x32\x11.dungeon.OpenGame\"#\n\x0eNewGameRequest\x12\x11\n\tgame_size\x18\x01 \x01(\x05\"\x11\n\x0fNewGameResponse\"\x08\n\x06Player\"\x12\n\x04Game\x12\n\n\x02id\x18\x01 \x01(\x03')




_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='dungeon.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='dungeon.Status.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msg', full_name='dungeon.Status.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=26,
  serialized_end=61,
)


_HEADER = _descriptor.Descriptor(
  name='Header',
  full_name='dungeon.Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='dungeon.Header.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msg_hash', full_name='dungeon.Header.msg_hash', index=1,
      number=2, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='token', full_name='dungeon.Header.token', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_response', full_name='dungeon.Header.is_response', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=63,
  serialized_end=158,
)


_OPENGAME = _descriptor.Descriptor(
  name='OpenGame',
  full_name='dungeon.OpenGame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='dungeon.OpenGame.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_num_players', full_name='dungeon.OpenGame.max_num_players', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cur_num_players', full_name='dungeon.OpenGame.cur_num_players', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=160,
  serialized_end=232,
)


_LOBBYSTATUSREQUEST = _descriptor.Descriptor(
  name='LobbyStatusRequest',
  full_name='dungeon.LobbyStatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=234,
  serialized_end=254,
)


_LOBBYSTATUSRESPONSE = _descriptor.Descriptor(
  name='LobbyStatusResponse',
  full_name='dungeon.LobbyStatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_running_games', full_name='dungeon.LobbyStatusResponse.num_running_games', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='open_games', full_name='dungeon.LobbyStatusResponse.open_games', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=256,
  serialized_end=343,
)


_NEWGAMEREQUEST = _descriptor.Descriptor(
  name='NewGameRequest',
  full_name='dungeon.NewGameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='game_size', full_name='dungeon.NewGameRequest.game_size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=345,
  serialized_end=380,
)


_NEWGAMERESPONSE = _descriptor.Descriptor(
  name='NewGameResponse',
  full_name='dungeon.NewGameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=382,
  serialized_end=399,
)


_PLAYER = _descriptor.Descriptor(
  name='Player',
  full_name='dungeon.Player',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=401,
  serialized_end=409,
)


_GAME = _descriptor.Descriptor(
  name='Game',
  full_name='dungeon.Game',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='dungeon.Game.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=411,
  serialized_end=429,
)

_HEADER.fields_by_name['status'].message_type = _STATUS
_LOBBYSTATUSRESPONSE.fields_by_name['open_games'].message_type = _OPENGAME
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.message_types_by_name['Header'] = _HEADER
DESCRIPTOR.message_types_by_name['OpenGame'] = _OPENGAME
DESCRIPTOR.message_types_by_name['LobbyStatusRequest'] = _LOBBYSTATUSREQUEST
DESCRIPTOR.message_types_by_name['LobbyStatusResponse'] = _LOBBYSTATUSRESPONSE
DESCRIPTOR.message_types_by_name['NewGameRequest'] = _NEWGAMEREQUEST
DESCRIPTOR.message_types_by_name['NewGameResponse'] = _NEWGAMERESPONSE
DESCRIPTOR.message_types_by_name['Player'] = _PLAYER
DESCRIPTOR.message_types_by_name['Game'] = _GAME

class Status(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STATUS

  # @@protoc_insertion_point(class_scope:dungeon.Status)

class Header(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HEADER

  # @@protoc_insertion_point(class_scope:dungeon.Header)

class OpenGame(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _OPENGAME

  # @@protoc_insertion_point(class_scope:dungeon.OpenGame)

class LobbyStatusRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOBBYSTATUSREQUEST

  # @@protoc_insertion_point(class_scope:dungeon.LobbyStatusRequest)

class LobbyStatusResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOBBYSTATUSRESPONSE

  # @@protoc_insertion_point(class_scope:dungeon.LobbyStatusResponse)

class NewGameRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NEWGAMEREQUEST

  # @@protoc_insertion_point(class_scope:dungeon.NewGameRequest)

class NewGameResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NEWGAMERESPONSE

  # @@protoc_insertion_point(class_scope:dungeon.NewGameResponse)

class Player(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PLAYER

  # @@protoc_insertion_point(class_scope:dungeon.Player)

class Game(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GAME

  # @@protoc_insertion_point(class_scope:dungeon.Game)


# @@protoc_insertion_point(module_scope)
